### ISSUE TITLE
Can this code can be used for 3 different classes

### ISSUE THREAD

**Issue by deepkshikha** [danielegrattarola/twitter-sentiment-cnn#16]
I have trained and tested successfully on provided dataset. will it works if i include more classes and on different dataset.

**Comment by danielegrattarola** [comment]
Different dataset: yes, you just have to format your input .csv as follows:

```
ItemID,Sentiment,SentimentSource,SentimentText
id_1,0,Sentiment140,Text text text
id_2,1,Sentiment140,Text text text
```
where the only important parts are the second and fourth columns (the other two can be anything you like, just put some placeholder text there). 

Different classes: no, because the whole workflow is intended for two classes (and I wasn't a really good programmer back then... still am not :)). If you wish to rewrite the whole data input pipeline, then you could do it. 

Cheers
